# Generated by Django 2.2.3 on 2019-09-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('domain', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('P', 'pending'), ('I', 'imported')], default='P', max_length=4)),
                ('last_import', models.DateTimeField()),
                ('script', models.CharField(default='', max_length=255)),
                ('running_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('C', 'change'), ('N', 'new')], default='C', max_length=4)),
                ('show', models.CharField(default='', max_length=255)),
                ('date', models.DateField(null=True)),
                ('date_flag', models.BooleanField(default=False)),
                ('doors', models.CharField(default='', max_length=50, null=True)),
                ('doors_flag', models.BooleanField(default=False)),
                ('venue', models.CharField(default='', max_length=255)),
                ('venue_flag', models.BooleanField(default=False)),
                ('main_act_show_time', models.DateTimeField(null=True)),
                ('main_act_show_time_flag', models.BooleanField(default=False)),
                ('main_act', models.CharField(default='', max_length=255)),
                ('main_act_flag', models.BooleanField(default=False)),
                ('support_act', models.CharField(default='', max_length=255)),
                ('support_act_flag', models.BooleanField(default=False)),
                ('show_description', models.TextField()),
                ('show_description_flag', models.BooleanField(default=False)),
                ('promoter', models.CharField(default='', max_length=255)),
                ('promoter_flag', models.BooleanField(default=False)),
                ('festival', models.CharField(default='', max_length=255, null=True)),
                ('festival_flag', models.BooleanField(default=False)),
                ('info_url', models.CharField(default='', max_length=255, null=True)),
                ('ticket_url', models.CharField(default='', max_length=255)),
                ('ticket_url_flag', models.BooleanField(default=False)),
                ('ticket_price', models.FloatField(null=True)),
                ('ticket_price_flag', models.BooleanField(default=False)),
                ('ticket_onsale_datetime', models.DateTimeField(null=True)),
                ('ticket_onsale_datetime_flag', models.BooleanField(default=False)),
                ('tickets_at_door_only', models.CharField(default='', max_length=255, null=True)),
                ('tickets_at_door_only_flag', models.BooleanField(default=False)),
                ('on_sale_soon', models.CharField(default='', max_length=255)),
                ('on_sale_soon_flag', models.BooleanField(default=False)),
                ('free', models.CharField(default='', max_length=255, null=True)),
                ('free_flag', models.BooleanField(default=False)),
                ('members_onsale_datetime', models.DateTimeField(null=True)),
                ('members_onsale_datetime_flag', models.BooleanField(default=False)),
                ('sold_out', models.BooleanField(default=False)),
                ('sold_out_flag', models.BooleanField(default=False)),
                ('show_type', models.CharField(default='', max_length=20)),
                ('show_type_flag', models.BooleanField(default=False)),
                ('listing_main_image', models.TextField(default='[]')),
                ('listing_main_image_flag', models.BooleanField(default=False)),
                ('listing_thumbnail', models.CharField(default='', max_length=255)),
                ('listing_thumbnail_flag', models.BooleanField(default=False)),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Crawler')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'ready for review'), ('P', 'pending'), ('A', 'approved'), ('S', 'sent to import'), ('D', 'deleted')], default='R', max_length=4)),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('new_record', models.IntegerField(default=0)),
                ('changed_record', models.IntegerField(default=0)),
                ('error_record', models.IntegerField(default=0)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Crawler')),
            ],
        ),
    ]
