# Generated by Django 2.2.5 on 2019-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20190926_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tickets_at_door_only',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
