# Generated by Django 2.2.5 on 2019-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20190926_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='free',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
