# Generated by Django 2.2.5 on 2019-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_auto_20190926_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('R', 'ready for review'), ('E', 'edited'), ('A', 'approved'), ('S', 'sent to import')], default='R', max_length=4),
        ),
    ]
