# Generated by Django 2.2.5 on 2019-10-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20190929_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
