# Generated by Django 2.2.5 on 2019-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_record_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='total_record',
            field=models.IntegerField(default=0),
        ),
    ]
