# Generated by Django 2.2.5 on 2019-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_log_total_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='info_url',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
