# Generated by Django 2.2.5 on 2019-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20191009_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='info_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
