# Generated by Django 2.2.5 on 2019-10-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_auto_20191009_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='sent_import',
            field=models.IntegerField(default=0),
        ),
    ]
