# Generated by Django 2.2.5 on 2019-10-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_auto_20191009_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('P', 'ready for review'), ('A', 'approved'), ('S', 'sent to import'), ('D', 'deleted')], default='P', max_length=4),
        ),
    ]
