# Generated by Django 2.2.5 on 2019-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_auto_20191014_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='canceled_record',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('R', 'ready for review'), ('E', 'edited'), ('A', 'approved'), ('S', 'sent to import'), ('C', 'canceled')], default='R', max_length=4),
        ),
    ]
