# Generated by Django 2.2.5 on 2019-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_auto_20191018_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='on_sale_soon',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
